name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: zmkfirmware/zmk-build-arm:stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: Zephyr Export
        run: west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app -b nice_nano_v2 \
            -- -DSHIELD=supermini -DZMK_CONFIG=$GITHUB_WORKSPACE/config

      - name: Package firmware
        run: cp build/zephyr/zmk.uf2 supermini_nice_nano_v2.uf2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: supermini_nice_nano_v2.uf2
